# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYEFF83xBSMqj5mdLjHxjboINZ2FilVk
"""

DPR_MODEL_PATH = 'facebook/dpr-question_encoder-single-nq-base'
DPR_CONTEXT_MODEL_PATH = 'facebook/dpr-ctx_encoder-single-nq-base'
TAPAS_MODEL_PATH = 'google/tapas-large-finetuned-wtq'