# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYEFF83xBSMqj5mdLjHxjboINZ2FilVk
"""

from dpr_retrieval import DPRTableRetrieval
from dtr_retrieval import DTRTableRetrieval
from reranker import rerank_tables

def main():
    query = "your query here"
    tables = [...]  # Load your tables data here
    method = "DPR"  # or "DTR"

    if method == "DPR":
        retriever = DPRTableRetrieval()
    elif method == "DTR":
        retriever = DTRTableRetrieval()
    else:
        raise ValueError("Unsupported method")

    retrieved_tables, similarities = retriever.retrieve(query, tables)
    reranked_tables = rerank_tables(retrieved_tables, similarities)

    print("Reranked Tables:", reranked_tables)

if __name__ == "__main__":
    main()