# -*- coding: utf-8 -*-
"""reranker

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYEFF83xBSMqj5mdLjHxjboINZ2FilVk
"""

def rerank_tables(tables, similarities):
    ranked_indices = similarities.argsort(descending=True)
    return [tables[i] for i in ranked_indices]